name: Build and Release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    # Add explicit permissions to fix the "Resource not accessible by integration" error
    permissions:
      contents: write
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Generate version
        id: version
        run: |
          COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d%H%M)
          echo "version=v0.1.0-${TIMESTAMP}-${COMMIT_SHA_SHORT}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: CLIPsight ${{ steps.version.outputs.version }}
          draft: false
          prerelease: true
          body: |
            Automated build from commit ${{ github.sha }}
            Generated on ${{ github.event.repository.updated_at }}
            
            This is an automated release built with PyInstaller.

  build-windows:
    needs: create-release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build with PyInstaller
        run: |
          pyinstaller --name CLIPsight --onedir --windowed --icon=search_icon.ico --add-data "search_icon.ico;." main.py
      
      - name: Zip directory
        run: |
          cd dist
          Compress-Archive -Path CLIPsight -DestinationPath CLIPsight-windows.zip
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./dist/CLIPsight-windows.zip
          asset_name: CLIPsight-${{ needs.create-release.outputs.version }}-windows.zip
          asset_content_type: application/zip

  build-macos:
    needs: create-release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build with PyInstaller
        run: |
          pyinstaller --name CLIPsight --onedir --windowed main.py
      
      - name: Create zip archive
        run: |
          cd dist
          zip -r CLIPsight-macos.zip CLIPsight.app
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./dist/CLIPsight-macos.zip
          asset_name: CLIPsight-${{ needs.create-release.outputs.version }}-macos.zip
          asset_content_type: application/zip

  build-linux:
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0
      
      - name: Build with PyInstaller
        run: |
          pyinstaller --name CLIPsight --onedir --windowed main.py
      
      - name: Create zip archive
        run: |
          cd dist
          zip -r CLIPsight-linux.zip CLIPsight
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./dist/CLIPsight-linux.zip
          asset_name: CLIPsight-${{ needs.create-release.outputs.version }}-linux.zip
          asset_content_type: application/zip
